import { Book, userInfo } from "@/api/Interface";

export const demoUserInfo: userInfo = {
  password: "demoPassword123",
  registration_date: new Date("2023-08-31"),
  username: "DemoUser123",
  profile_picture: "profile-pic-url.jpg",
  book_count: 10,
  dark_mode: true,
  column_count: 3,
  genres: {
    "Self-help": "blue",
    Productivity: "green",
    Habits: "yellow",
    Mindset: "red",
    Lifestyle: "purple",
  },
  categories: ["Practice", "Interesting", "Lesson", "Habit"],
  last_upload: "2023-08-30",
  notion_auth: "notion-auth-token-123",
  verified_email: true,
  subscription: true,
  stripe_customer_id: "12345678",
  has_trial_period: false,
  subscription_end: new Date("2024-08-31"),
};

export const demoBooks: Book[] = [
  {
    annotated: false,
    genre: ["Self-help", "Productivity", "Habits"],
    _id: "12345678",
    userID: "63b98299d4a24e32474d3ff7",
    cover_image:
      "https://m.media-amazon.com/images/I/81bGKUa1e0L._AC_UF894,1000_QL80_.jpg",
    isbn: "9781847941848",
    author: "James Clear",
    title: "Atomic Habits",
    rating: 4,
    length: 320,
    upload_date: "2021-05-16T21:59:34.000Z",
    summary: `Lesson 1) Small habits make a big difference It is so easy to overestimate the importance of one defining moment and underestimate the value of making small improvements on a daily basis.
    
Lesson 2) Forget about setting goals. Focus on your system instead. Goals are about the results you want to achieve. Systems are about the processes that lead to those results.If you’re having trouble changing your habits, the problem isn’t you. The problem is your system.
    
Lesson 3) Build identity-based habitsThe key to building lasting habits is focusing on creating a new identity first. Your current behaviors are simply a reflection of your current identity. What you do now is a mirror image of the type of person you believe that you are (either consciously or subconsciously).`,
    deleted: false,
    highlights: [
      {
        category: [],
        _id: "12345678",
        Text: "A habit is a routine or behavior that is performed regularly—and, in many cases, automatically.",
        Page: 9,
        LocationStart: 124,
        LocationEnd: 124,
        Date: "Sunday, 16 May 2021 22:01:46",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "A habit is a routine or behavior that is performed regularly—and, in many cases, automatically.",
        Page: 9,
        LocationStart: 124,
        LocationEnd: 124,
        Date: "Sunday, 16 May 2021 22:01:46",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: ["Bars"],
        _id: "12345678",
        Text: "“the aggregation of marginal gains,”",
        Page: 14,
        LocationStart: 200,
        LocationEnd: 200,
        Date: "Monday, 17 May 2021 06:51:46",
        notes: "",
        starred: true,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "if you broke down everything you could think of that goes into riding a bike, and then improve it by 1 percent, you will get a significant increase when you put them all together.”",
        Page: 14,
        LocationStart: 202,
        LocationEnd: 203,
        Date: "Monday, 17 May 2021 06:52:04",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "Too often, we convince ourselves that massive success requires massive action.",
        Page: 15,
        LocationStart: 223,
        LocationEnd: 224,
        Date: "Monday, 17 May 2021 06:55:35",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "if you can get 1 percent better each day for one year, you’ll end up thirty-seven times better by the time you’re done. Conversely, if you get 1 percent worse each day for one year, you’ll decline nearly down to zero. What starts as a small win or a minor setback accumulates into something much more.",
        Page: 15,
        LocationStart: 227,
        LocationEnd: 230,
        Date: "Monday, 17 May 2021 06:57:18",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "Habits are the compound interest of self-improvement.",
        Page: 16,
        LocationStart: 235,
        LocationEnd: 235,
        Date: "Monday, 17 May 2021 06:58:28",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "The same way that money multiplies through compound interest, the effects of your habits multiply as you repeat them.",
        Page: 16,
        LocationStart: 235,
        LocationEnd: 236,
        Date: "Monday, 17 May 2021 06:58:45",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
    ],
  },
  {
    annotated: false,
    genre: ["Self-help", "Mindset", "Lifestyle"],
    _id: "12345678",
    userID: "63b98299d4a24e32474d3ff7",
    cover_image:
      "https://m.media-amazon.com/images/I/71QKQ9mwV7L._AC_UF894,1000_QL80_.jpg",
    isbn: "9780062837509",
    author: "Mark Manson",
    title: "The Subtle Art of Not Giving a Fck",
    rating: 5,
    summary:
      "Finding something important and meaningful in your life is the most productive use of your time and energy. This is true because every life has problems associated with it and finding meaning in your life will help you sustain the effort needed to overcome the particular problems you face. Thus, we can say that the key to living a good life is not giving a fuck about more things, but rather, giving a fuck only about the things that align with your personal values.",
    deleted: false,
    length: 224,
    upload_date: "2021-05-16T21:59:34.000Z",
    highlights: [
      {
        category: [],
        _id: "12345678",
        Text: "Self-improvement and success often occur together. But that doesn’t necessarily mean they’re the same thing.",
        LocationStart: 71,
        LocationEnd: 72,
        Date: "Monday, 3 April 2023 00:01:26",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "Ironically, this fixation on the positive—on what’s better, what’s superior—only serves to remind us over and over again of what we are not, of what we lack, of what we should have been but failed to be.",
        LocationStart: 82,
        LocationEnd: 83,
        Date: "Monday, 3 April 2023 00:09:29",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "A confident man doesn’t feel a need to prove that he’s confident.",
        LocationStart: 85,
        LocationEnd: 85,
        Date: "Monday, 3 April 2023 00:10:35",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "giving too many fucks is bad for your mental health.",
        LocationStart: 93,
        LocationEnd: 94,
        Date: "Monday, 3 April 2023 00:12:06",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "The key to a good life is not giving a fuck about more; it’s giving a fuck about less, giving a fuck about only what is true and immediate and important.",
        LocationStart: 95,
        LocationEnd: 96,
        Date: "Monday, 3 April 2023 00:12:31",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "“I feel like shit, but who gives a fuck?”",
        LocationStart: 128,
        LocationEnd: 128,
        Date: "Monday, 3 April 2023 00:45:23",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "Our crisis is no longer material; it’s existential, it’s spiritual.",
        LocationStart: 134,
        LocationEnd: 134,
        Date: "Monday, 3 April 2023 00:46:12",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "Because there’s an infinite amount of things we can now see or know, there are also an infinite number of ways we can discover that we don’t measure up, that we’re not good enough, that things aren’t as great as they could be.",
        LocationStart: 135,
        LocationEnd: 137,
        Date: "Monday, 3 April 2023 00:46:49",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
    ],
  },
  {
    annotated: false,
    genre: [],
    _id: "12345678",
    userID: "63b98299d4a24e32474d3ff7",
    cover_image: "https://m.media-amazon.com/images/I/71dUSlTVOwL.jpg",
    isbn: "9780822100461",
    author: "Rick Rubin",
    title: "The Creative Act",
    rating: 0,
    summary:
      "Legendary music producer Rick Rubin’s The Creative Act: A Way of Being is a mind-bending series of meditations on what it means to be an artist and creator. Through 78 philosophical musings, Rubin shares the wisdom that we are all artists, offers helpful mental frames for creating and moving through roadblocks, and helps you develop an understanding of what it means to operate as an artist in the world. His book offers an endless stream of timeless wisdom that makes it one to revisit many times over the years.",
    deleted: false,
    length: 224,
    upload_date: "2021-05-16T21:59:34.000Z",
    highlights: [
      {
        category: [],
        _id: "12345678",
        Text: "If you have an idea you’re excited about and you don’t bring it to life, it’s not uncommon for the idea to find its voice through another maker. This isn’t because the other artist stole your idea, but because the idea’s time has come.",
        LocationStart: 159,
        LocationEnd: 161,
        Date: "Tuesday, 11 April 2023 19:27:30",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "In this great unfolding, ideas and thoughts, themes and songs and other works of art exist in the aether and ripen on schedule, ready to find expression in the physical world.",
        LocationStart: 161,
        LocationEnd: 162,
        Date: "Tuesday, 11 April 2023 19:31:02",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "We are all translators for messages the universe is broadcasting.",
        LocationStart: 163,
        LocationEnd: 164,
        Date: "Tuesday, 11 April 2023 19:36:31",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "The best artists tend to be the ones with the most sensitive antennae to draw in the energy resonating at a particular moment.",
        LocationStart: 164,
        LocationEnd: 164,
        Date: "Tuesday, 11 April 2023 19:36:49",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "energetic more than tactile, intuitively perceived more than consciously recorded.",
        LocationStart: 172,
        LocationEnd: 172,
        Date: "Tuesday, 11 April 2023 19:38:24",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "Practicing a way of being that allows you to see the world through uncorrupted, innocent eyes can free you to act in concert with the universe’s timetable.",
        LocationStart: 184,
        LocationEnd: 185,
        Date: "Tuesday, 11 April 2023 19:40:12",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "There’s a time for certain ideas to arrive, and they find a way to express themselves through us.",
        LocationStart: 186,
        LocationEnd: 189,
        Date: "Tuesday, 11 April 2023 19:40:27",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "To the mind, this material appears to come from within. But that’s an illusion. There are tiny fragments of the vastness of Source stored within us. These precious wisps arise from the unconscious like vapor, and condense to form a thought. An idea.",
        LocationStart: 201,
        LocationEnd: 202,
        Date: "Tuesday, 11 April 2023 19:41:36",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
      {
        category: [],
        _id: "12345678",
        Text: "If something strikes me as interesting or beautiful, first I live that experience. Only afterward might I attempt to understand it.",
        LocationStart: 232,
        LocationEnd: 232,
        Date: "Tuesday, 11 April 2023 19:45:04",
        notes: "",
        starred: false,
        deleted: false,
        last_updated: "",
      },
    ],
  },
];
