import React, { useState, useEffect } from "react";
import styles from "../styles/Book.module.scss";
import { Book } from "@/api/Interface";
import Tilt from "react-parallax-tilt";
import userAuthenticated from "@/helpers/UserAuthenticated";
import { usePalette } from "react-palette";
import { useRouter } from "next/router";
import StarBorderIcon from "@mui/icons-material/StarBorder";
import StarIcon from "@mui/icons-material/Star";
import cleanAuthor from "@/helpers/cleanAuthor";
import imageValid from "@/helpers/ImageValidation";
import rateBookApi from "@/api/Books/RateBook";

interface BookProps {
  book: Book;
  index: number;
}

const BookComponent = ({ book, index }: BookProps) => {
  //Getting the most vibrant color
  const { data } = usePalette(book.cover_image);
  const [restrictions, setRestrictions] = useState(true);
  const [imageIsValid, setImageIsValid] = useState(false);
  const [isMouseInside, setIsMouseInside] = useState(false);
  const [rating, setRating] = useState(book.rating);
  const router = useRouter();

  //Tracking the mouse position to make the hover effect
  const handleMouseEnter = () => {
    setIsMouseInside(true);
  };
  const handleMouseLeave = () => {
    setIsMouseInside(false);
  };
  //Tracking the mouse position to make the hover effect

  //Setting restrictions on page load
  useEffect(() => {
    setRestrictions(!userAuthenticated());
  }, []);

  //Whenever a book cover is changed we need to check if it is valid or not and update the state
  useEffect(() => {
    const verifyImage = async () => {
      try {
        const imageIsValid = await imageValid(book.cover_image);
        setImageIsValid(imageIsValid);
      } catch (err) {
        console.log("from image", err);
        setImageIsValid(false);
      }
    };

    verifyImage();
  }, [book.cover_image]);

  return (
    <div
      className={styles.Book}
      onClick={() => router.push(`Book/${restrictions ? index : book._id}`)}
    >
      <div
        className={styles.ImageSection}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <div
          className={isMouseInside ? `${styles.blurEffect}` : ""}
          style={{ "--background-color": data.vibrant } as React.CSSProperties}
        ></div>
        <Tilt
          glareEnable={true}
          glareMaxOpacity={0.4}
          glarePosition="all"
          glareReverse={true}
          glareBorderRadius="0px"
          tiltEnable={true}
          // trackOnWindow={true}
          className={styles.ImageHolder}
          perspective={850}
        >
          {restrictions && index === 0 ? (
            <h3>
              Login required to get autogenerated book covers, and the ability
              to add your own.
            </h3>
          ) : !imageIsValid && !restrictions ? (
            <h3>Cannot find image, feel free to add your own</h3>
          ) : !restrictions && imageIsValid ? (
            <img
              draggable="false"
              alt="ebook cover image"
              src={book.cover_image}
              className="image"
            />
          ) : null}
        </Tilt>
      </div>
      <div className={styles.Book_Meta_Section}>
        <div className={styles.Meta_center}>
          <h3>{book.title}</h3>
          <p>{cleanAuthor(book.author)}</p>
          {restrictions ? null : (
            <p>
              {[...Array(5)].map((eachStar, i) => {
                const isFilled = i < rating;
                const starIcon = isFilled ? <StarIcon /> : <StarBorderIcon />;

                return (
                  <span
                    key={i}
                    id="star"
                    onClick={(e) => {
                      e.stopPropagation();
                      const newRating = isFilled ? i : i + 1;
                      setRating(newRating);
                      rateBookApi({ book_id: book._id, data: newRating });
                    }}
                  >
                    {starIcon}
                  </span>
                );
              })}
            </p>
          )}
        </div>
      </div>
    </div>
  );
};

export default BookComponent;
